"""Add thumbnail_url column to Property

Revision ID: 541f08fdff48
Revises: 45eb264e00d6
Create Date: 2024-10-13 06:02:31.262766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '541f08fdff48'
down_revision = '45eb264e00d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_url', sa.String(length=200), nullable=True))

    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('application_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant', schema=None) as batch_op:
        batch_op.alter_column('application_status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_url')

    # ### end Alembic commands ###
